FROM ubuntu:24.04 AS base

ENV TOOLCHAIN="arm-zephyr-eabi"
ENV ZSDK_VERSION="0.17.1"
ARG ZEPHYR_SDK_DIR="/opt"
ENV ZEPHYR_SDK=${ZEPHYR_SDK_DIR}/zephyr-sdk-${ZSDK_VERSION}
ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

RUN apt-get -y update && \
	apt-get --no-install-recommends -y install \
		ccache \
		cmake \
		device-tree-compiler \
		dfu-util \
		file \
		g++-multilib \
		gcc \
		gcc-multilib \
		git \
		gperf \
		libmagic1 \
		libsdl2-dev \
		make \
		ninja-build \
		python3-dev \
		python3-pip \
		python3-setuptools \
		python3-tk \
		python3-wheel \
		wget \
		xz-utils \
		&& \
	apt-get clean -y && \
	apt-get autoremove --purge -y && \
	rm -rf /var/lib/apt/lists/*



FROM base AS step-sdk

WORKDIR "${ZEPHYR_SDK_DIR}"
ADD https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZSDK_VERSION}/zephyr-sdk-${ZSDK_VERSION}_linux-x86_64_minimal.tar.xz zephyr-sdk.tar.xz
RUN tar xf zephyr-sdk.tar.xz
WORKDIR "${ZEPHYR_SDK}"
RUN ./setup.sh -t ${TOOLCHAIN} -h



FROM base
ARG UID=1000
ARG GID=1000
ARG USERNAME="ubuntu"

ENV ZEPHYR_BASE=/home/${USERNAME}/workspace/zephyr
ENV PATH="${ZEPHYR_BASE}/scripts:${PATH}"

# Install Python dependencies
RUN	pip3 install --no-cache-dir --break-system-packages \
		-r https://raw.githubusercontent.com/zephyrproject-rtos/zephyr/main/scripts/requirements.txt \
		-r https://raw.githubusercontent.com/zephyrproject-rtos/mcuboot/main/scripts/requirements.txt \
		GitPython imgtool junitparser junit2html numpy protobuf PyGithub \
		pylint sh statistics west \
		nrf-regtool~=7.0.0 && \
	pip3 check

USER ${USERNAME}
WORKDIR /home/${USERNAME}/workspace

COPY --from=step-sdk /opt/zephyr-sdk-${ZSDK_VERSION} /opt/zephyr-sdk-${ZSDK_VERSION}

RUN west init && \
	west update
